import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, GraduationCap, MapPin, Sparkles } from "lucide-react";
import UniversityFooter from "@/components/layout/UniversityFooter";
import Navbar from "@/components/layout/Navbar";
import ScrollReveal from "./ScrollReveal";
import FAQAccordion from "./FAQAccordion";
import SectionHeading from "./SectionHeading";

const imageMap = { "study-in-uk-ireland": "/images/countries/united_kingdom.png", "study-in-europe": "/images/footer/sorbonne.jpg", "study-in-usa": "/images/countries/usa.png", "study-in-australia-new-zealand": "/images/countries/UAE_Dubai_Banner.webp", "study-abroad": "/images/hero-student.png", "mbbs-abroad": "/images/guidance/counselling.png", "phd-programs-abroad": "/images/study-india/guidance-student.webp", "test-prep-language-training": "/images/study-india/online-degree-student.webp", "sop-lor-and-documentation-support": "/images/how-we-help/documentation-application.png", "education-loan": "/images/guidance/scholarship.png", "career-counseling-admission-guidance": "/images/how-we-help/personalised-counselling.png", "travel-forex-assistance": "/images/guidance/departure.png", "about-us": "/images/callback-student.webp", "contact-us": "/images/counselling.webp" };

function Cards({ items, icon = false }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item, index) => <article key={`${item}-${index}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_12px_35px_-28px_#003870] transition-transform duration-300 hover:-translate-y-1 hover:shadow-[0_18px_45px_-28px_#003870] motion-reduce:transition-none">{icon ? <Sparkles size={21} className="text-brand-teal-ink" aria-hidden="true" /> : <span className="text-xs font-bold text-brand-teal-ink">{String(index + 1).padStart(2, "0")}</span>}<h3 className="mt-3 text-base font-bold leading-6 text-brand-navy">{item}</h3></article>)}</div>; }

export default function SourcePage({ slug, page }) {
  const image = imageMap[slug] || "/images/hero-student.png";
  const active = slug.startsWith("study-") || ["mbbs-abroad", "phd-programs-abroad"].includes(slug) ? "Study Abroad" : slug === "about-us" ? "About Us" : "Student Services";
  return <><Navbar active={active} /><main className="overflow-hidden bg-[#f7f9fb] text-slate-700"><section className="border-b border-slate-200 bg-[#edf6f5] pb-12 pt-32 sm:pb-16 sm:pt-36"><div className="mx-auto grid w-full max-w-[1240px] items-center gap-10 px-4 sm:px-5 lg:grid-cols-2 lg:gap-14 lg:px-6"><ScrollReveal direction="left"><nav aria-label="Breadcrumb" className="mb-7 flex flex-wrap gap-2 text-xs text-slate-600"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">{page.title}</span></nav><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-teal-ink">{page.eyebrow || "University Yatra"}</p><h1 className="mt-4 text-[38px] font-bold leading-[1.12] tracking-[-0.04em] text-brand-navy sm:text-5xl lg:text-[60px]">{page.title}</h1><p className="mt-5 max-w-xl text-base leading-8 text-slate-600">{page.description}</p>{page.chips && <div className="mt-6 flex flex-wrap gap-2">{page.chips.map((chip) => <span key={chip} className="rounded-full border border-brand-teal/30 bg-white px-3 py-2 text-xs font-semibold text-brand-navy">{chip}</span>)}</div>}<Link href="/contact" className="mt-7 inline-flex items-center gap-3 rounded-xl bg-brand-navy px-5 py-3.5 text-sm font-bold text-white transition-colors hover:bg-brand-navy-dark focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-teal-ink">Book a Free Consultation <ArrowRight size={18} aria-hidden="true" /></Link></ScrollReveal><ScrollReveal direction="right"><div className="relative aspect-[4/3] overflow-hidden rounded-3xl bg-white p-4 shadow-[0_18px_55px_-25px_#00387055]"><div className="flex h-full items-center justify-center overflow-hidden rounded-2xl bg-[#e7f4f2]"><Image src={image} alt={`${page.title} visual`} fill sizes="(min-width: 1024px) 580px, 100vw" className="object-cover" /></div></div></ScrollReveal></div></section>
    <div className="mx-auto w-full max-w-[1240px] px-4 py-14 sm:px-5 sm:py-20 lg:px-6"><ScrollReveal><section><SectionHeading eyebrow="Strategic guidance" title="Make the next decision with clarity" description={page.guidance} /><Cards items={page.help || []} icon /></section></ScrollReveal>{page.universities && <ScrollReveal><section className="mt-16"><SectionHeading eyebrow="Universities" title="Explore university options" description="Review universities and locations available on the source page." /><Cards items={page.universities} /></section></ScrollReveal>}{page.destinations && <section className="mt-16"><SectionHeading eyebrow="Destinations" title="Popular study destinations" /><Cards items={page.destinations} /></section>}{page.courses && <section className="mt-16"><SectionHeading eyebrow="Courses" title="Top in-demand courses" /><Cards items={page.courses} /></section>}{page.comparison && <section className="mt-16"><SectionHeading eyebrow="Academic overview" title="Compare the pathway" /><div className="grid gap-5 md:grid-cols-2">{page.comparison.map((item) => <article key={item.title} className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-xl font-bold text-brand-navy">{item.title}</h3><ul className="mt-4 space-y-3">{item.items.map((line) => <li key={line} className="flex gap-3 text-sm leading-6 text-slate-600"><CheckCircle2 size={18} className="mt-1 shrink-0 text-brand-teal-ink" aria-hidden="true" />{line}</li>)}</ul></article>)}</div></section>}{page.costs && <section className="mt-16"><SectionHeading eyebrow="Cost planning" title="Understand the cost of studying" description="The source page provides the following planning figures and notes." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.costs.map((cost) => <div key={cost} className="rounded-2xl border border-brand-teal/20 bg-[#eaf5f3] p-5 text-sm font-semibold leading-7 text-brand-navy">{cost}</div>)}</div></section>}<section className="mt-16"><div className="grid gap-8 rounded-3xl bg-brand-navy p-7 text-white sm:p-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-teal">University Yatra support</p><h2 className="mt-3 text-2xl font-bold sm:text-3xl">Start with the right guidance</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/75">Choosing the right country, course and university is crucial for your next step. Start with expert guidance to explore suitable options for your profile.</p></div><Link href="/contact" className="inline-flex items-center justify-center gap-3 rounded-xl bg-brand-teal px-5 py-3.5 text-sm font-bold text-brand-navy-dark hover:bg-white">Contact Us <ArrowRight size={18} aria-hidden="true" /></Link></div></section>{page.faqs && <section className="mt-16"><SectionHeading eyebrow="FAQs" title="Questions students ask" /><FAQAccordion items={page.faqs} /></section>}</div></main><UniversityFooter /></>;
}
